import io
import re
import datetime

from flask import Blueprint, request, jsonify, send_file
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter

from legacy_core import current_user

bp=Blueprint(
    "v4_report_tools",__name__,
    url_prefix="/v4/report-tools",
    static_folder="static",static_url_path="/static"
)

def _safe_sheet_name(name):
    name=re.sub(r'[\[\]\:\*\?\/\\]'," ",str(name or "Report")).strip() or "Report"
    return name[:31]

def _cell_text(v):
    if v is None:
        return ""
    return str(v).strip()[:32000]

@bp.post("/excel")
def excel_export():
    u=current_user()
    if not u or u["role"] not in ("MD","GM"):
        return jsonify({"ok":False,"error":"Not authorized"}),403

    payload=request.get_json(silent=True) or {}
    title=_cell_text(payload.get("title") or "CRM Report")
    page_url=_cell_text(payload.get("url") or "")
    generated=datetime.datetime.now().strftime("%d-%m-%Y %I:%M %p")
    metrics=payload.get("metrics") or []
    tables=payload.get("tables") or []

    wb=Workbook()
    ws=wb.active
    ws.title=_safe_sheet_name("Summary")

    gold="D9A928"
    navy="0C2D49"
    white="FFFFFF"
    thin=Side(style="thin",color="54718A")

    ws["A1"]=title
    ws["A1"].font=Font(size=16,bold=True,color=gold)
    ws.merge_cells("A1:D1")
    ws["A2"]="Generated By"; ws["B2"]=u["full_name"]
    ws["A3"]="Role"; ws["B3"]=u["role"]
    ws["A4"]="Company"; ws["B4"]=u["company_code"] or "Both Companies"
    ws["A5"]="Generated On"; ws["B5"]=generated
    ws["A6"]="Source Page"; ws["B6"]=page_url

    row=8
    if metrics:
        ws.cell(row,1,"Dashboard / Page Metrics")
        ws.cell(row,1).font=Font(bold=True,color=gold)
        row+=1
        for c,h in enumerate(["Metric","Value"],1):
            cell=ws.cell(row,c,h); cell.font=Font(bold=True,color=white); cell.fill=PatternFill("solid",fgColor=navy)
        row+=1
        for item in metrics[:300]:
            if not isinstance(item,dict): continue
            ws.cell(row,1,_cell_text(item.get("label")))
            ws.cell(row,2,_cell_text(item.get("value")))
            row+=1

    for ti,t in enumerate(tables[:30],1):
        if not isinstance(t,dict): continue
        rows=t.get("rows") or []
        if not rows: continue
        name=_safe_sheet_name(t.get("name") or f"Table {ti}")
        if name in wb.sheetnames:
            name=_safe_sheet_name(f"{name[:25]} {ti}")
        sh=wb.create_sheet(name)
        for r_idx,rowdata in enumerate(rows[:10000],1):
            if not isinstance(rowdata,list): continue
            for c_idx,val in enumerate(rowdata[:80],1):
                cell=sh.cell(r_idx,c_idx,_cell_text(val))
                cell.alignment=Alignment(vertical="top",wrap_text=True)
                cell.border=Border(bottom=thin)
                if r_idx==1:
                    cell.font=Font(bold=True,color=white)
                    cell.fill=PatternFill("solid",fgColor=navy)
        sh.freeze_panes="A2"
        for c in range(1,min(sh.max_column,80)+1):
            width=12
            for rr in range(1,min(sh.max_row,80)+1):
                width=max(width,min(35,len(str(sh.cell(rr,c).value or ""))+2))
            sh.column_dimensions[get_column_letter(c)].width=width

    if len(wb.sheetnames)==1 and not metrics:
        ws["A8"]="No visible table/metric data was found on this page."
        ws["A9"]="The page can still be printed or shared through WhatsApp."

    for c,w in {"A":25,"B":48,"C":22,"D":22}.items():
        ws.column_dimensions[c].width=w

    bio=io.BytesIO()
    wb.save(bio); bio.seek(0)
    filename=re.sub(r"[^A-Za-z0-9_-]+","_",title).strip("_")[:70] or "CRM_Report"
    filename+=datetime.datetime.now().strftime("_%Y-%m-%d_%H%M")+".xlsx"
    return send_file(
        bio,
        as_attachment=True,
        download_name=filename,
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

def install_report_tools(app):
    if app.extensions.get("v45_report_tools_installed"):
        return

    @app.after_request
    def _inject_report_tools(response):
        try:
            if response.status_code!=200:
                return response
            ctype=(response.headers.get("Content-Type") or "").lower()
            if "text/html" not in ctype:
                return response
            u=current_user()
            if not u or u["role"] not in ("MD","GM"):
                return response

            data=response.get_data(as_text=True)
            if "</body>" not in data or "v45-management-tools" in data:
                return response

            tag='<script id="v45-management-tools" src="/v4/report-tools/static/report_tools.js?v=4.5.0" defer></script>'
            data=data.replace("</body>",tag+"</body>",1)
            response.set_data(data)
            response.headers["Content-Length"]=str(len(response.get_data()))
        except Exception:
            pass
        return response

    app.extensions["v45_report_tools_installed"]=True
